### PR TITLE
Create compton-conf_it.desktop

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by stefonarch** [comment]
Looking ath the others they are all different between them. Are
[Desktop Entry]
#TRANSLATIONS_DIR=translations

needed? I guess not. Maybe uniform them all?

**Comment by palinek** [comment]
> Are ... needed? I guess not. 

Nope. Only the language specific keys are _grepped_ in build time...

**Comment by stefonarch** [comment]
Removed the unused lines in the other .desktop files.

**Comment by agaida** [comment]
GTM

**Pull request merged**
