### PR TITLE
Show the configurator if compton is installed;

### PR DESCRIPTION
**Pull request by agaida**
testing compton-conf don't make any sense in this case

### CODE REVIEW

**Comment by pmattern** [comment]
Stating `compton-conf` itself as value of key `TryExec` indeed makes hardly ever sense given that both the desktop entry file and the binary are normally provided by the same binary package. Also, trying to prevent users from using ComptonConf in a way that doesn't have any effect seems reasonable. Not sure whether the proposed solution really makes sense, though.

Right now ComptonConf can very well be started from the menus without having an effect when Compton isn't installed. But I figure this is a situation where users can find out the problem rather easily.
After applying this PR ComptonConf will simply not appear in the menus any longer when Compton isn't installed. And I guess this is a situation much more difficult to understand for users.

Wouldn't it be an option to make ComptonConf depend on Compton which it doesn't so far? A context where installing ComptonConf without Compton makes sense will hardly ever exist.

Also, none of the solutions implemented or proposed so far is covering the scenario that ComptonConf does not have an effect because Compton is installed but simply not running. Is this something we should address, e. g. by having ComptonConf throw a warning when it's launched but Compton isn't active?
Btw. this could be considered in ObConf-Qt as well.

**Comment by agaida** [comment]
Mhh - changing dependencies is a little bit overkill - there are some situations where it is not wise to run compton-conf when compton is not installed nor running - the user change some values and save the changes. Somewhen $user install and start compton - with exactly these saved values - and trust me, theses values aren't the settings one want to have normally. Even better, these settings remain after a possible purge of compton-conf, because no package manager clean up user files. Not the best of all situations. 

Imho the TryExec would make compton-conf a little bit more complete and thats a good thing.

**Comment by agaida** [comment]
Reading both posts again - a dependency to compton is the better solution - @pmattern would you be so kind and add this to the wiki/build instructions?

**Comment by pmattern** [comment]
> @pmattern would you be so kind and add this to the wiki/build instructions?

I sure can. Probably in file `README.md` of ComptonConf itself and the wiki page about building from source, right?

**Pull request closed without merging**
