### PR TITLE
Create compton.conf_hr.ts

### PR DESCRIPTION
**Pull request by zvacet**

### CODE REVIEW

**Comment by palinek** [comment]
Did you edit the .ts by hand?

All translations like:
```xml
        <translation type="Sjena"></translation>
```
aren't correct/valid.

You can try translating with [linguist](http://doc.qt.io/qt-5/qtlinguist-index.html)...

**Comment by zvacet** [comment]
Thank you for your suggestion. I translated LXQT earlier ( on Github) and now that translations are gone. Why? 


     On Thursday, October 29, 2015 8:30 AM, palinek <notifications@github.com> wrote:
   

 Did you edit the .ts by hand?All translations like:        <translation type="Sjena"></translation>aren't correct/valid.You can try translating with linguist...—

**Comment by palinek** [comment]
> I translated LXQT earlier ( on Github) and now that translations are gone. Why?

What translations are you talking about (files, links, PRs) ?

**Comment by zvacet** [comment]
Files of lxqt-panel but I will translate it again. Is it good practice to put translaton tu master branch? Thank you for all your time and help.
 


     On Thursday, October 29, 2015 12:52 PM, palinek <notifications@github.com> wrote:
   

 
I translated LXQT earlier ( on Github) and now that translations are gone. Why?
What translations are you talking about (files, links, PRs) ?—

**Comment by pmattern** [comment]
@zvacet 
In all of the numerous PRs you've been submitting in the meantime some translations are missing (`<translation type="unfinished"></translation>`) and some were translated without removing attribute `type="unfinished"` like in `<translation type="unfinished">Pokušaj #%1</translation>` from `lxqt-sudo`.
Like this we cannot merge them.

What I don't understand is that @palinek has been pointing you to this kind problem in his comment above and recommended using `Qt Linguist` which could have avoided all these errors and hence probably a lot of superfluous work.
So I'm confused what's going on here. Some kind of misunderstanding?

Regarding the loss of translations you may consider adding a comment to lxde/lxqt#796 if you can name some distinct components that were affected, too.

**Comment by zvacet** [comment]
@Peter Mattern
I did like I was suggested and after that all my translation are done via Qt linguist. I don´t know how is possible that kind of error if I´m using that program. Can I check that tomorrow, because I need some sleep right now?
best regards
zvacet
 


     On Thursday, October 29, 2015 10:09 PM, Peter Mattern <notifications@github.com> wrote:
   

 @zvacet 
In all of the numerous PRs you've been submitting in the meantime some translations are missing (<translation type="unfinished"></translation>) and some were translated without removing attribute type="unfinished" like in <translation type="unfinished">Pokušaj #%1</translation> from lxqt-sudo.
Like this we cannot merge them.What I don't understand is that @palinek has been pointing you to this kind problem in his comment above and recommended using Qt Linguist which could have avoided all these errors and hence probably a lot of superfluous work.
So I'm confused what's going on here. Some kind of misunderstanding?Regarding the loss of translations you may consider adding a comment to lxde/lxqt#796 if you can name some distinct components that were affected, too.—

**Comment by palinek** [comment]
The `<translation type="unfinished">*</translation>` is not an error. It just points that the translation is not fully completed yet.

@zvacet In linguist you have to put the "green tick" to the translation when you are finished with it. Another question is why aren't you translating all the text but just a fraction of them?

**Comment by palinek** [comment]
> Like this we cannot merge them.

@pmattern why? Is there an agreement we refuse the translation if it doesn't translate all of the existing phrases?

**Comment by pmattern** [comment]
Of course missing translations aren't the reason to avoid merging. (Besides I think it would be better if all strings were covered at once. It's not too many after all.)

The reason are the errors. Many translations took place in attribute 'type' like `<translation type="Postavke specijalnih efekata"></translation>` in this PR or still are erroneously tagged "unfinished", see example in my last comment.
And by now at least one of these two problems is affecting several strings in all of the PRs.

**Comment by zvacet** [comment]
@Peter Mattern and @palinek 

Thank you for your patience and advices. I fixed translation using green tick as palinek suggested. Now I´m interested how to merge translations in one as you @pmattern  suggested. Sorry for ignorance.

**Comment by pmattern** [comment]
The translation proposed by #23 seems syntactically correct now.

Still several strings remain untranslated.
As discussed earlier this is no hindrance to merge the PR yet it would be better to have the translation complete at once. Is there any particular reason why you didn't translate everything? Any chance you could add the missing pieces?

Regarding Git you could just have squashed the additional commits of #23 into branch `patch-1` and pushed that branch again to github.com/zvacet. This commit (#22) would have got updated automatically that way.
Explaining how to fix this is actually beyond the scope of a bug report. But as you seem to have spent a lot of time already I'd suggest to proceed like this
* Copy the valid version of `compton.conf_hr.ts` outside your local Git repo and delete the latter.
* Checkout the compton-conf repo from upstream again `git clone https://github.com/lxde/compton-conf.git`. Change into the directory, add your own repo `git remote add zvacet https://github.com/zvacet/compton-conf.git` and fetch all relevant information `git fetch --all`.
* Run `git checkout -b patch-1` to re-create that branch and checkout into it. Make a commit featuring the actual translation basically as you did before but just copy the file instead of editing. Upload your changes to your GitHub account `git push --force zvacet patch-1:patch-1`.

This should hopefully update this PR, #23 won't be needed any longer.
If you should be interested in helping out with translations it would probably good to learn more about Git. An IMO pretty good source is http://www.git-scm.com/book.

All in all I'd suggest having these translations reviewed by a second native speaker if feasible.

**Pull request closed without merging**
