### PR TITLE
providing direction for commiters for fedora inclusion

### PR DESCRIPTION
**Pull request by cmpunches**
providing direction for commiters

### CODE REVIEW

**Comment by agaida** [comment]
Isn't this better placed in a fedora bug? To be true i see no sense in merging this upstream, this is a downstream problem.

**Comment by tsujan** [comment]
> Isn't this better placed in a fedora bug?

I agree. When it's a Fedora problem, it shouldn't be here.

**Comment by cmpunches** [comment]
Hey agaida.  Thanks for the reply.  I do not think downstream is where it can receive upstream without a full dependency tree list as translatable identifiers for those libraries.  Without this, even if a package were created there would be no guarantee that the package had all the required packages listed where present on other distros and assumed.  If we mention Fedora not being present, which is an issue admittedly, I do think that listing why would be important to resolving that. Otherwise you're creating a guessing game for the packager unless they pour through the code. Which may or may not be what you want.

**Comment by tsujan** [comment]
As for me, I didn't understand your reasoning but I think this sentence can be removed altogether: "The tool is missing in Fedora so far."

**Comment by cmpunches** [comment]
FYI - I would be happy to assume a package maintainer role for Fedora if this is a need for this project.  I am seeing that it is hoping to have them for major distros.  Let me know.

**Comment by agaida** [comment]
ok, we can close this right now: https://github.com/lxde/compton-conf/issues/26

I'm not willing to merge fedora specific things upstream - as i'm not willing to do that for debian, arch, suse or any other. but i would really accept a patch for the readme. one will find the needed dependencies mentioned by pmattern

**Comment by agaida** [comment]
or more explicit: For debian the build dependencies would be
```
Build-Depends: debhelper (>= 10),
               libconfig-dev,
               libkf5windowsystem-dev,
               libqt5svg5-dev,
               libqt5x11extras5-dev,
               libx11-dev,
               lxqt-build-tools (>= 0.3.2~) 
```
One could take that as reference.

**Comment by cmpunches** [comment]
Fair enough.  I'll try to get a comprehensive list together of the translated names and build an RPM for inclusion request.  I'd like to see this in Fedora.  It may also be related to the fact that there is no official compton package.  If I can get it into the rpmfusion-free repos will it be updated?

**Comment by agaida** [comment]
as i don't know the packaging of lxqt-build-tools outside of debian - it might be that cmake, qt-dev-tool or qt-linguist are needed

**Comment by cmpunches** [comment]
I'll build it in a vanilla environment and verify to be sure.

**Comment by agaida** [comment]
we have nothing to do with any downstreams - unless we are involved in one. You might talk with lupinix in the LXQt IRC channel - freenode lxde

**Comment by cmpunches** [comment]
Will do -- thanks.

**Comment by agaida** [comment]
Btw - for compton the situation is far more complex - for what ever reason they don't want to improve, release, fork or do any other thing that wont make sense with compton. Sorry, some people including me try to talk with the compton guys. But nothing happend. Maybe an unfriendly fork would help.

Unless anything like that happend one could consider compton dead in the water.

**Comment by cmpunches** [comment]
That's a difficult thing.  I myself would not be able to maintain the code for compton, it's a little above me at the moment, but I can certainly mirror to a fork, add periodic release tags, and then generate packages from the release tags.  I'll consider it.

**Comment by agaida** [comment]
https://github.com/chjj/compton/issues/300 - you will find several of these bugs in the compton tracker

**Pull request closed without merging**
